replicaCount: 2

image:
  repository: nginx
  tag: "1.21.1"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: my-registry-secret

service:
  type: ClusterIP
  port: 3000

resources:
  requests:
    cpu: 10m
    memory: 20Mi
  limits:
    cpu: 15m
    memory: 50Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
