{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"email\": \"%s\"}}}" .Values.imagePullSecrets.dockerServer .Values.imagePullSecrets.dockerUsername .Values.imagePullSecrets.dockerPassword .Values.imagePullSecrets.dockerEmail | b64enc }}
{{- end }}
