name: Deploy AKS
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_registry_url }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_API_KEY }}

      - name: Build, tag, and push image to azure-ACR
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: demo-nodejs
        run: |
          cd sample-nodeapp
          docker build -t ${{ secrets.ACR_registry_url }}/$IMAGE_NAME:$IMAGE_TAG .
          docker push ${{ secrets.ACR_registry_url }}/$IMAGE_NAME:$IMAGE_TAG 
  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Deploy with Helm
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: demo-nodejs
        run: |
          helm upgrade --install nodeapp ./nodeapp \       
            --set imagePullSecrets.create=false \
            --set image.repository=${{ secrets.ACR_REGISTRY_URL }}/$IMAGE_NAME \
            --set image.tag=$IMAGE_TAG



